-- pubDB to papersdb migrate script

-- fix errors
UPDATE user SET name='Pandora Lam' WHERE name='PandoraLam';
UPDATE user SET name='Idanis Diaz' WHERE name='idanis';
DELETE FROM user WHERE name='nelson';
UPDATE publication SET updated=null WHERE updated='0000-00-00';
UPDATE author SET email=null WHERE trim(email)='';
UPDATE author SET email=null WHERE `name`='Lake, Robert';

DELETE ua FROM user_author ua LEFT JOIN `user` ON user.login=ua.login WHERE user.login is null;

DELETE FROM user WHERE verified=0;

--

ALTER TABLE `user` DROP PRIMARY KEY,
      ADD COLUMN `ID` bigint(20) NOT NULL auto_increment FIRST,
      ADD PRIMARY KEY (`ID`) USING BTREE;

ALTER TABLE `user`
      ADD COLUMN `VERSION` int(11) NOT NULL AFTER `ID`,
      CHANGE `access_level` `ACCESS_TYPE` int(11) NULL AFTER `VERSION`,
      CHANGE `email` `EMAIL` varchar(255) NULL AFTER `ACCESS_TYPE`,
      CHANGE `name` `FAMILY_NAMES` varchar(255) NULL AFTER `EMAIL`,
      ADD COLUMN `GIVEN_NAMES` varchar(255) NULL AFTER `FAMILY_NAMES`,
      ADD COLUMN `LAST_LOGIN` datetime NULL AFTER `GIVEN_NAMES`,
      CHANGE `login` `LOGIN` varchar(255) NULL AFTER `LAST_LOGIN`,
      CHANGE `password` `PASSWORD` varchar(255) NULL AFTER `LOGIN`,
      ADD COLUMN `REGISTRATION_DATE` datetime NULL AFTER `PASSWORD`,
      CHANGE `verified` `IS_VERIFIED` tinyint(1) NULL AFTER `REGISTRATION_DATE`,
      DROP COLUMN `search`,
      DROP COLUMN `comments`,
      DROP COLUMN `options`,
      ADD UNIQUE INDEX `EMAIL` (`EMAIL`) USING BTREE,
      ADD UNIQUE INDEX `LOGIN` (`LOGIN`) USING BTREE,
      ENGINE=InnoDB ROW_FORMAT=Compact;

ALTER TABLE user MODIFY COLUMN ID BIGINT(20) NOT NULL;

-- breakup name into first and last names

UPDATE user SET given_names=TRIM(LEFT(family_names,LOCATE(' ',family_names)));
UPDATE user SET family_names=TRIM(SUBSTR(family_names,LOCATE(' ',family_names)));

--

ALTER TABLE author ENGINE=InnoDB;

ALTER TABLE `author` DROP PRIMARY KEY,
      CHANGE COLUMN `author_id` `ID` bigint(20) NOT NULL  FIRST,
      ADD PRIMARY KEY (`ID`) USING BTREE;

ALTER TABLE author
      ADD COLUMN VERSION INT(11) NOT NULL COMMENT '' AFTER `ID`,
      CHANGE COLUMN `email` EMAIL VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL COMMENT '',
      CHANGE COLUMN `name` FAMILY_NAMES VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL COMMENT '',
      ADD COLUMN GIVEN_NAMES VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL COMMENT '' AFTER family_names,
      CHANGE COLUMN `title` TITLE VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL COMMENT '',
      ADD CONSTRAINT EMAIL UNIQUE KEY(EMAIL);

ALTER TABLE author
      DROP COLUMN webpage,
      DROP COLUMN organization;


UPDATE author SET given_names=TRIM(SUBSTR(family_names,LOCATE(',',family_names)+1));
UPDATE author SET family_names=TRIM(LEFT(family_names,LOCATE(',',family_names)-1));

--

ALTER TABLE user_author ENGINE=InnoDB;

ALTER TABLE user_author
      ADD COLUMN USER_ID BIGINT(20) COMMENT '' NOT NULL,
      MODIFY COLUMN AUTHOR_ID BIGINT(20) COMMENT '' NOT NULL;

UPDATE user_author,`user` SET user_id=user.id WHERE user.login=user_author.login;

ALTER TABLE user_author
      DROP PRIMARY KEY,
      DROP COLUMN login,
      ADD INDEX FKF581647FA32D0B24 (AUTHOR_ID),
      ADD INDEX FKF581647FAF21CD3 (USER_ID),
      ADD PRIMARY KEY (USER_ID, AUTHOR_ID);

ALTER TABLE user_author
      ADD CONSTRAINT FKF581647FA32D0B24 FOREIGN KEY FKF581647FA32D0B24 (AUTHOR_ID)
          REFERENCES author (ID) ON UPDATE NO ACTION ON DELETE NO ACTION,
      ADD CONSTRAINT FKF581647FAF21CD3 FOREIGN KEY FKF581647FAF21CD3 (USER_ID)
          REFERENCES user (ID) ON UPDATE NO ACTION ON DELETE NO ACTION;

\q

--

DROP TABLE additional_info;
DROP TABLE aicml_positions;
DROP TABLE aicml_staff;
DROP TABLE attachment_types;
DROP TABLE author_interest;
DROP TABLE cat_info;
DROP TABLE cat_vopts;
DROP TABLE category;
DROP TABLE collaboration;
DROP TABLE extra_info;
DROP TABLE help_fields;
DROP TABLE info;
DROP TABLE interest;
DROP TABLE pointer;
DROP TABLE pub_add;
DROP TABLE pub_author;
DROP TABLE pub_cat;
DROP TABLE pub_cat_info;
DROP TABLE pub_col;
DROP TABLE pub_pending;
DROP TABLE pub_rankings;
DROP TABLE pub_valid;
DROP TABLE tag_ml_history;
DROP TABLE venue;
DROP TABLE venue_occur;
DROP TABLE venue_rankings;
DROP TABLE venue_vopts;
DROP TABLE vopts;
ALTER TABLE publication DROP PRIMARY KEY,
      DROP COLUMN pub_id,
      DROP COLUMN title,
      DROP COLUMN paper,
      DROP COLUMN abstract,
      DROP COLUMN keywords,
      DROP COLUMN published,
      DROP COLUMN venue_id,
      DROP COLUMN extra_info,
      DROP COLUMN submit,
      DROP COLUMN rank_id,
      DROP COLUMN updated,
      DROP COLUMN user;
ALTER TABLE publication ENGINE=InnoDB;
ALTER TABLE publication ADD COLUMN DISCRIMINATOR VARCHAR(31) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL COMMENT '',
      ADD COLUMN ID BIGINT(20) COMMENT '' NOT NULL,
      ADD COLUMN VERSION INT(11) NOT NULL COMMENT '',
      ADD COLUMN DATE DATETIME NOT NULL COMMENT '',
      ADD COLUMN NAME VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL COMMENT '',
      ADD COLUMN BOOK_TITLE VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL COMMENT '',
      ADD COLUMN EDITION VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL COMMENT '',
      ADD COLUMN EDITOR VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL COMMENT '',
      ADD COLUMN CHAPTER VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL COMMENT '',
      ADD COLUMN NUMBER VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL COMMENT '',
      ADD COLUMN PAGES VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL COMMENT '',
      ADD COLUMN VOLUME VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL COMMENT '',
      ADD COLUMN INSTITUTION VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL COMMENT '',
      ADD COLUMN THESIS_TYPE VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL COMMENT '',
      ADD COLUMN BOOK_PUBLISHER TINYBLOB NULL DEFAULT NULL COMMENT '',
      ADD COLUMN PUBLISHER_ID BIGINT(20) NOT NULL COMMENT '', ADD INDEX FK_PUBLICATION_PUBLISHER (PUBLISHER_ID), ADD PRIMARY KEY (ID);
CREATE TABLE author_ranked (
    ID BIGINT(20) NOT NULL,
    VERSION INT(11) NOT NULL,
    RANK INT(11) NULL DEFAULT NULL,
    AUTHOR_ID BIGINT(20) NOT NULL,
    PAPER_ID BIGINT(20) NULL DEFAULT NULL,
    INDEX FK_AUTHOR_RANKED_AUTHOR (AUTHOR_ID),
    INDEX FK_AUTHOR_RANKED_PAPER (PAPER_ID),
    PRIMARY KEY (ID)
) ENGINE=InnoDB COLLATE=latin1_swedish_ci;
CREATE TABLE paper (
    ID BIGINT(20) NOT NULL,
    VERSION INT(11) NOT NULL,
    DOI VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    ABSTRACT TEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    CUSTOM_RANKING VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    DB_INSERT_DATE DATETIME NULL DEFAULT NULL,
    DB_UPDATE_DATE DATETIME NULL DEFAULT NULL,
    EXTRA_INFORMATION TEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    KEYWORDS VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    PAPER_DATE DATE NULL DEFAULT NULL,
    PUBLIC TINYINT(1) NULL DEFAULT NULL,
    RANKING_ID INT(11) NULL DEFAULT NULL,
    TITLE VARCHAR(500) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
    USER_TAGS VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    PUBLICATION_ID BIGINT(20) NULL DEFAULT NULL,
    SUBMITTED_BY_USER_ID BIGINT(20) NULL DEFAULT NULL,
    INDEX FK486196CC5699AAF (SUBMITTED_BY_USER_ID),
    INDEX FK_PAPER_PUBLICATION (PUBLICATION_ID),
    CONSTRAINT TITLE UNIQUE KEY(TITLE, PUBLICATION_ID),
    CONSTRAINT DOI UNIQUE KEY(DOI),
    PRIMARY KEY (ID)
) ENGINE=InnoDB COLLATE=latin1_swedish_ci;
CREATE TABLE paper_attachment (
    PAPER_ID BIGINT(20) NOT NULL,
    ATTACHMENT VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    INDEX FK8C91A5D6EB041BB0 (PAPER_ID)
) ENGINE=InnoDB COLLATE=latin1_swedish_ci;
CREATE TABLE paper_collaboration (
    PAPER_ID BIGINT(20) NOT NULL,
    COLLABORATION_ID VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
    INDEX FK9F371092EB041BB0 (PAPER_ID),
    PRIMARY KEY (PAPER_ID, COLLABORATION_ID)
) ENGINE=InnoDB COLLATE=latin1_swedish_ci;
CREATE TABLE paper_paper (
    FROM_PAPER_ID BIGINT(20) NOT NULL,
    TO_PAPER_ID BIGINT(20) NOT NULL,
    INDEX FK7B92D4D9F82834A5 (FROM_PAPER_ID),
    INDEX FK7B92D4D953E258F4 (TO_PAPER_ID),
    PRIMARY KEY (FROM_PAPER_ID, TO_PAPER_ID)
) ENGINE=InnoDB COLLATE=latin1_swedish_ci;
CREATE TABLE paper_url (
    PAPER_ID BIGINT(20) NOT NULL,
    URL VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    INDEX FKB7EFFBFCEB041BB0 (PAPER_ID)
) ENGINE=InnoDB COLLATE=latin1_swedish_ci;
CREATE TABLE publisher (
    ID BIGINT(20) NOT NULL,
    VERSION INT(11) NOT NULL,
    NAME VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
    RANKING_ID VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    CONSTRAINT NAME UNIQUE KEY(NAME),
    PRIMARY KEY (ID)
) ENGINE=InnoDB COLLATE=latin1_swedish_ci;
ALTER TABLE author_ranked ADD CONSTRAINT FK_AUTHOR_RANKED_PAPER FOREIGN KEY (PAPER_ID) REFERENCES paper (ID) ON UPDATE NO ACTION ON DELETE NO ACTION,
      ADD CONSTRAINT FK_AUTHOR_RANKED_AUTHOR FOREIGN KEY (AUTHOR_ID) REFERENCES author (ID) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE paper ADD CONSTRAINT FK486196CC5699AAF FOREIGN KEY (SUBMITTED_BY_USER_ID) REFERENCES user (ID) ON UPDATE NO ACTION ON DELETE NO ACTION,
      ADD CONSTRAINT FK_PAPER_PUBLICATION FOREIGN KEY (PUBLICATION_ID) REFERENCES publication (ID) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE paper_attachment ADD CONSTRAINT FK8C91A5D6EB041BB0 FOREIGN KEY (PAPER_ID) REFERENCES paper (ID) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE paper_collaboration ADD CONSTRAINT FK9F371092EB041BB0 FOREIGN KEY (PAPER_ID) REFERENCES paper (ID) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE paper_paper ADD CONSTRAINT FK7B92D4D953E258F4 FOREIGN KEY (TO_PAPER_ID) REFERENCES paper (ID) ON UPDATE NO ACTION ON DELETE NO ACTION,
      ADD CONSTRAINT FK7B92D4D9F82834A5 FOREIGN KEY (FROM_PAPER_ID) REFERENCES paper (ID) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE paper_url ADD CONSTRAINT FKB7EFFBFCEB041BB0 FOREIGN KEY (PAPER_ID) REFERENCES paper (ID) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE publication ADD CONSTRAINT FK_PUBLICATION_PUBLISHER FOREIGN KEY FK_PUBLICATION_PUBLISHER (PUBLISHER_ID) REFERENCES publisher (ID) ON UPDATE NO ACTION ON DELETE NO ACTION;
